function curr = niceOutput(prog)
% makes a nice output report while the function is running
% --------------------------------------------------------
% prog          Cell of progess values
%
% curr          Current progress (formated)
% --------------------------------------------------------


% set up output stream
curr = strcat(...
    '\n',...
    'Plant Optimum                    %-17s\n',...
    'Iteration Number                 %-3d/%-3d\n',...
    'Total Plant Time                 %-4d\n',...
    'Last Iteration Wall Time         %-7.2f\n',...
    'Total Wall Time                  %-7.2f\n',...
    '\n',...
    'Current Setpoint                 [ %6.4f, %-5.2f]\n',...
    'Current Plant Cost               %-17.2f\n',...
    '\n',...
    'Optimum Setpoint                 [ %6.4f, %-5.2f]\n',...
    'Optimum Plant Cost               %-17.2f\n',...
    '\n',...
    'Percent Change [r1|r2|phi]       [ %6.3f | %6.3f | %6.3f ]\n',...
    '\n');


a = sprintf(curr,prog{:});
clc
fprintf(a)

end