function createfigure(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 20-Feb-2018 16:00:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.078579117330463 0.178688524590164 0.861141011840691 0.804918032786888]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Plant Optimum','LineWidth',4,'LineStyle',':',...
    'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'DisplayName','Transient Model','MarkerSize',15,'Marker','.',...
    'LineWidth',3,...
    'Color',[0.756862759590149 0 0.26274511218071]);

% Create plot
plot(X3,Y3,'DisplayName','Standard Model','MarkerSize',15,'Marker','.',...
    'LineWidth',3,...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create xlabel
xlabel('Time [s]','FontWeight','bold','FontSize',30);

% Create ylabel
ylabel('Productivity','FontWeight','bold','FontSize',30);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-20 320]);
% Set the remaining axes properties
set(axes1,'FontSize',24,'LineWidth',3,'XTick',[0 1000 2000 3000],'YTick',...
    zeros(1,0));
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.472615261543794 0.286447186578052 0.419050059815349 0.221231305448315],...
    'FontSize',30);

