function PBstruct = ProblemStructure()

PBstruct = struct();

%% Simulation 
PBstruct.x0 = [ 0.4; 0.4; 0.05; 0.05; 0.05; 0.05; ...
                0.4; 0.4 ; 0.07; 0.07; 0.06; ...
                0.4; 0.4; 0.07; 0.07; 0.06;       0.4; 0.4; 0.07; 0.07; 0.06]; 

%% Options solver/optimizer

PBstruct.fmincon_options = optimoptions(@fmincon,'Algorithm','sqp' , ...'interior-point'   'sqp' 'active-set'
                                        'MaxIter',1000000,... 
                                        'Display', 'off',...
                                        'MaxFunEvals',1000000,...
                                        'TolFun',1e-8,...
                                        'TolCon',1e-8,...
                                        'TolX',1e-8,...
                                        'FinDiffType','central' ,... % ,...%'forward' (default), or 'central' 
                                        'ScaleProblem','obj-and-constr');
                                    
PBstruct.fmincon_options_2 = optimoptions(@fmincon,'Algorithm','sqp' , ...'interior-point'   'sqp' 'active-set'
                                        'MaxIter',1000000,... 
                                        'Display', 'off',...
                                        'MaxFunEvals',1000000,...
                                        'TolFun',1e-8,...
                                        'TolCon',1e-8,...
                                        'TolX',1e-8,...
                                        'FinDiffType','central',... % ,...%'forward' (default), or 'central' 
                                        'ScaleProblem','obj-and-constr');                                    
                                         
                                     
PBstruct.fsolve_options = optimset('Algorithm','trust-region-reflective',...levenberg-marquardt     trust-region-reflective
                          'LargeScale','on',...
                          'Diagnostics','off',...
                          'Display','off' ,...  final
                          'FunValCheck','on',...
                          'MaxFunEvals',100000,...
                          'MaxIter',100000,...
                          'TolFun',1e-9, ...
                          'TolX',1e-9, ...
                          'TolCon',1e-9);

%% 


end